deployment:
  tasks:
    - export DEPLOYPATH=/home/diwrhl18hcfw/public_html/sesiime.com/index.html
    - mkdir -p $DEPLOYPATH
    - rsync -av --progress ./ $DEPLOYPATH --exclude='.git' --exclude='cpanel.yml'